language: objective-c
osx_image: xcode9

script:
- xcodebuild build -project Swifty3D.xcodeproj -scheme Swifty3D -sdk iphonesimulator
- xcodebuild build -project Swifty3D.xcodeproj -scheme Swifty3D -sdk iphoneos
- xcodebuild build -project Swifty3D.xcodeproj -scheme Swifty3DDemo -sdk iphonesimulator